server:
  port: 8888

spring:
  application:
    name: ConfigService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
