server:
  port: 8761 # Port par défaut pour Eureka Server

spring:
  application:
    name: DiscoveryService # Nom du service Eureka Server

eureka:
  client:
    register-with-eureka: false # Le Discovery Service ne s'inscrit pas lui-même
    fetch-registry: false       # Pas besoin de récupérer les autres services
  server:
    enable-self-preservation: false # Désactiver pour éviter les problèmes de test en local

logging:
  level:
    com.netflix.eureka: DEBUG  # Logs détaillés pour Eureka
